<?php
return [
    "AF" => ["id" => "1", "name" => "Afghanistan", "symbol" => "؋", "currency" => "AFN"],
    "AX" => ["id" => "2", "name" => "Aland Islands", "symbol" => "€", "currency" => "EUR"],
    "AL" => ["id" => "3", "name" => "Albania", "symbol" => "Lek", "currency" => "ALL"],
    "DZ" => ["id" => "4", "name" => "Algeria", "symbol" => "دج", "currency" => "DZD"],
    "AS" => ["id" => "5", "name" => "American Samoa", "symbol" => "$", "currency" => "USD"],
    "AD" => ["id" => "6", "name" => "Andorra", "symbol" => "€", "currency" => "EUR"],
    "AO" => ["id" => "7", "name" => "Angola", "symbol" => "Kz", "currency" => "AOA"],
    "AI" => ["id" => "8", "name" => "Anguilla", "symbol" => "$", "currency" => "XCD"],
    "AQ" => ["id" => "9", "name" => "Antarctica", "symbol" => "$", "currency" => "AAD"],
    "AG" => ["id" => "10", "name" => "Antigua and Barbuda", "symbol" => "$", "currency" => "XCD"],
    "AR" => ["id" => "11", "name" => "Argentina", "symbol" => "$", "currency" => "ARS"],
    "AM" => ["id" => "12", "name" => "Armenia", "symbol" => "֏", "currency" => "AMD"],
    "AW" => ["id" => "13", "name" => "Aruba", "symbol" => "ƒ", "currency" => "AWG"],
    "AU" => ["id" => "14", "name" => "Australia", "symbol" => "$", "currency" => "AUD"],
    "AT" => ["id" => "15", "name" => "Austria", "symbol" => "€", "currency" => "EUR"],
    "AZ" => ["id" => "16", "name" => "Azerbaijan", "symbol" => "m", "currency" => "AZN"],
    "BS" => ["id" => "17", "name" => "Bahamas", "symbol" => "B$", "currency" => "BSD"],
    "BH" => ["id" => "18", "name" => "Bahrain", "symbol" => ".د.ب", "currency" => "BHD"],
    "BD" => ["id" => "19", "name" => "Bangladesh", "symbol" => "৳", "currency" => "BDT"],
    "BB" => ["id" => "20", "name" => "Barbados", "symbol" => "Bds$", "currency" => "BBD"],
    "BY" => ["id" => "21", "name" => "Belarus", "symbol" => "Br", "currency" => "BYN"],
    "BE" => ["id" => "22", "name" => "Belgium", "symbol" => "€", "currency" => "EUR"],
    "BZ" => ["id" => "23", "name" => "Belize", "symbol" => "$", "currency" => "BZD"],
    "BJ" => ["id" => "24", "name" => "Benin", "symbol" => "CFA", "currency" => "XOF"],
    "BM" => ["id" => "25", "name" => "Bermuda", "symbol" => "$", "currency" => "BMD"],
    "BT" => ["id" => "26", "name" => "Bhutan", "symbol" => "Nu.", "currency" => "BTN"],
    "BO" => ["id" => "27", "name" => "Bolivia", "symbol" => "Bs.", "currency" => "BOB"],
    "BQ" => ["id" => "28", "name" => "Bonaire, Sint Eustatius and Saba", "symbol" => "$", "currency" => "USD"],
    "BA" => ["id" => "29", "name" => "Bosnia and Herzegovina", "symbol" => "KM", "currency" => "BAM"],
    "BW" => ["id" => "30", "name" => "Botswana", "symbol" => "P", "currency" => "BWP"],
    "BV" => ["id" => "31", "name" => "Bouvet Island", "symbol" => "kr", "currency" => "NOK"],
    "BR" => ["id" => "32", "name" => "Brazil", "symbol" => "R$", "currency" => "BRL"],
    "IO" => ["id" => "33", "name" => "British Indian Ocean Territory", "symbol" => "$", "currency" => "USD"],
    "BN" => ["id" => "34", "name" => "Brunei Darussalam", "symbol" => "B$", "currency" => "BND"],
    "BG" => ["id" => "35", "name" => "Bulgaria", "symbol" => "Лв.", "currency" => "BGN"],
    "BF" => ["id" => "36", "name" => "Burkina Faso", "symbol" => "CFA", "currency" => "XOF"],
    "BI" => ["id" => "37", "name" => "Burundi", "symbol" => "FBu", "currency" => "BIF"],
    "KH" => ["id" => "38", "name" => "Cambodia", "symbol" => "KHR", "currency" => "KHR"],
    "CM" => ["id" => "39", "name" => "Cameroon", "symbol" => "FCFA", "currency" => "XAF"],
    "CA" => ["id" => "40", "name" => "Canada", "symbol" => "$", "currency" => "CAD"],
    "CV" => ["id" => "41", "name" => "Cape Verde", "symbol" => "$", "currency" => "CVE"],
    "KY" => ["id" => "42", "name" => "Cayman Islands", "symbol" => "$", "currency" => "KYD"],
    "CF" => ["id" => "43", "name" => "Central African Republic", "symbol" => "FCFA", "currency" => "XAF"],
    "TD" => ["id" => "44", "name" => "Chad", "symbol" => "FCFA", "currency" => "XAF"],
    "CL" => ["id" => "45", "name" => "Chile", "symbol" => "$", "currency" => "CLP"],
    "CN" => ["id" => "46", "name" => "China", "symbol" => "¥", "currency" => "CNY"],
    "CX" => ["id" => "47", "name" => "Christmas Island", "symbol" => "$", "currency" => "AUD"],
    "CC" => ["id" => "48", "name" => "Cocos (Keeling] Islands", "symbol" => "$", "currency" => "AUD"],
    "CO" => ["id" => "49", "name" => "Colombia", "symbol" => "$", "currency" => "COP"],
    "KM" => ["id" => "50", "name" => "Comoros", "symbol" => "CF", "currency" => "KMF"],
    "CG" => ["id" => "51", "name" => "Congo", "symbol" => "FC", "currency" => "XAF"],
    "CD" => ["id" => "52", "name" => "Congo, Democratic Republic of the Congo", "symbol" => "FC", "currency" => "CDF"],
    "CK" => ["id" => "53", "name" => "Cook Islands", "symbol" => "$", "currency" => "NZD"],
    "CR" => ["id" => "54", "name" => "Costa Rica", "symbol" => "₡", "currency" => "CRC"],
    "CI" => ["id" => "55", "name" => "Cote D'Ivoire", "symbol" => "CFA", "currency" => "XOF"],
    "HR" => ["id" => "56", "name" => "Croatia", "symbol" => "kn", "currency" => "HRK"],
    "CU" => ["id" => "57", "name" => "Cuba", "symbol" => "$", "currency" => "CUP"],
    "CW" => ["id" => "58", "name" => "Curacao", "symbol" => "ƒ", "currency" => "ANG"],
    "CY" => ["id" => "59", "name" => "Cyprus", "symbol" => "€", "currency" => "EUR"],
    "CZ" => ["id" => "60", "name" => "Czech Republic", "symbol" => "Kč", "currency" => "CZK"],
    "DK" => ["id" => "61", "name" => "Denmark", "symbol" => "Kr.", "currency" => "DKK"],
    "DJ" => ["id" => "62", "name" => "Djibouti", "symbol" => "Fdj", "currency" => "DJF"],
    "DM" => ["id" => "63", "name" => "Dominica", "symbol" => "$", "currency" => "XCD"],
    "DO" => ["id" => "64", "name" => "Dominican Republic", "symbol" => "$", "currency" => "DOP"],
    "EC" => ["id" => "65", "name" => "Ecuador", "symbol" => "$", "currency" => "USD"],
    "EG" => ["id" => "66", "name" => "Egypt", "symbol" => "ج.م", "currency" => "EGP"],
    "SV" => ["id" => "67", "name" => "El Salvador", "symbol" => "$", "currency" => "USD"],
    "GQ" => ["id" => "68", "name" => "Equatorial Guinea", "symbol" => "FCFA", "currency" => "XAF"],
    "ER" => ["id" => "69", "name" => "Eritrea", "symbol" => "Nfk", "currency" => "ERN"],
    "EE" => ["id" => "70", "name" => "Estonia", "symbol" => "€", "currency" => "EUR"],
    "ET" => ["id" => "71", "name" => "Ethiopia", "symbol" => "Nkf", "currency" => "ETB"],
    "FK" => ["id" => "72", "name" => "Falkland Islands (Malvinas]", "symbol" => "£", "currency" => "FKP"],
    "FO" => ["id" => "73", "name" => "Faroe Islands", "symbol" => "Kr.", "currency" => "DKK"],
    "FJ" => ["id" => "74", "name" => "Fiji", "symbol" => "FJ$", "currency" => "FJD"],
    "FI" => ["id" => "75", "name" => "Finland", "symbol" => "€", "currency" => "EUR"],
    "FR" => ["id" => "76", "name" => "France", "symbol" => "€", "currency" => "EUR"],
    "GF" => ["id" => "77", "name" => "French Guiana", "symbol" => "€", "currency" => "EUR"],
    "PF" => ["id" => "78", "name" => "French Polynesia", "symbol" => "₣", "currency" => "XPF"],
    "TF" => ["id" => "79", "name" => "French Southern Territories", "symbol" => "€", "currency" => "EUR"],
    "GA" => ["id" => "80", "name" => "Gabon", "symbol" => "FCFA", "currency" => "XAF"],
    "GM" => ["id" => "81", "name" => "Gambia", "symbol" => "D", "currency" => "GMD"],
    "GE" => ["id" => "82", "name" => "Georgia", "symbol" => "ლ", "currency" => "GEL"],
    "DE" => ["id" => "83", "name" => "Germany", "symbol" => "€", "currency" => "EUR"],
    "GH" => ["id" => "84", "name" => "Ghana", "symbol" => "GH₵", "currency" => "GHS"],
    "GI" => ["id" => "85", "name" => "Gibraltar", "symbol" => "£", "currency" => "GIP"],
    "GR" => ["id" => "86", "name" => "Greece", "symbol" => "€", "currency" => "EUR"],
    "GL" => ["id" => "87", "name" => "Greenland", "symbol" => "Kr.", "currency" => "DKK"],
    "GD" => ["id" => "88", "name" => "Grenada", "symbol" => "$", "currency" => "XCD"],
    "GP" => ["id" => "89", "name" => "Guadeloupe", "symbol" => "€", "currency" => "EUR"],
    "GU" => ["id" => "90", "name" => "Guam", "symbol" => "$", "currency" => "USD"],
    "GT" => ["id" => "91", "name" => "Guatemala", "symbol" => "Q", "currency" => "GTQ"],
    "GG" => ["id" => "92", "name" => "Guernsey", "symbol" => "£", "currency" => "GBP"],
    "GN" => ["id" => "93", "name" => "Guinea", "symbol" => "FG", "currency" => "GNF"],
    "GW" => ["id" => "94", "name" => "Guinea-Bissau", "symbol" => "CFA", "currency" => "XOF"],
    "GY" => ["id" => "95", "name" => "Guyana", "symbol" => "$", "currency" => "GYD"],
    "HT" => ["id" => "96", "name" => "Haiti", "symbol" => "G", "currency" => "HTG"],
    "HM" => ["id" => "97", "name" => "Heard Island and McDonald Islands", "symbol" => "$", "currency" => "AUD"],
    "VA" => ["id" => "98", "name" => "Holy See (Vatican City State]", "symbol" => "€", "currency" => "EUR"],
    "HN" => ["id" => "99", "name" => "Honduras", "symbol" => "L", "currency" => "HNL"],
    "HK" => ["id" => "100", "name" => "Hong Kong", "symbol" => "$", "currency" => "HKD"],
    "HU" => ["id" => "101", "name" => "Hungary", "symbol" => "Ft", "currency" => "HUF"],
    "IS" => ["id" => "102", "name" => "Iceland", "symbol" => "kr", "currency" => "ISK"],
    "IN" => ["id" => "103", "name" => "India", "symbol" => "₹", "currency" => "INR"],
    "ID" => ["id" => "104", "name" => "Indonesia", "symbol" => "Rp", "currency" => "IDR"],
    "IR" => ["id" => "105", "name" => "Iran, Islamic Republic of", "symbol" => "﷼", "currency" => "IRR"],
    "IQ" => ["id" => "106", "name" => "Iraq", "symbol" => "د.ع", "currency" => "IQD"],
    "IE" => ["id" => "107", "name" => "Ireland", "symbol" => "€", "currency" => "EUR"],
    "IM" => ["id" => "108", "name" => "Isle of Man", "symbol" => "£", "currency" => "GBP"],
    "IL" => ["id" => "109", "name" => "Israel", "symbol" => "₪", "currency" => "ILS"],
    "IT" => ["id" => "110", "name" => "Italy", "symbol" => "€", "currency" => "EUR"],
    "JM" => ["id" => "111", "name" => "Jamaica", "symbol" => "J$", "currency" => "JMD"],
    "JP" => ["id" => "112", "name" => "Japan", "symbol" => "¥", "currency" => "JPY"],
    "JE" => ["id" => "113", "name" => "Jersey", "symbol" => "£", "currency" => "GBP"],
    "JO" => ["id" => "114", "name" => "Jordan", "symbol" => "ا.د", "currency" => "JOD"],
    "KZ" => ["id" => "115", "name" => "Kazakhstan", "symbol" => "лв", "currency" => "KZT"],
    "KE" => ["id" => "116", "name" => "Kenya", "symbol" => "KSh", "currency" => "KES"],
    "KI" => ["id" => "117", "name" => "Kiribati", "symbol" => "$", "currency" => "AUD"],
    "KP" => ["id" => "118", "name" => "Korea, Democratic People's Republic of", "symbol" => "₩", "currency" => "KPW"],
    "KR" => ["id" => "119", "name" => "Korea, Republic of", "symbol" => "₩", "currency" => "KRW"],
    "XK" => ["id" => "120", "name" => "Kosovo", "symbol" => "€", "currency" => "EUR"],
    "KW" => ["id" => "121", "name" => "Kuwait", "symbol" => "ك.د", "currency" => "KWD"],
    "KG" => ["id" => "122", "name" => "Kyrgyzstan", "symbol" => "лв", "currency" => "KGS"],
    "LA" => ["id" => "123", "name" => "Lao People's Democratic Republic", "symbol" => "₭", "currency" => "LAK"],
    "LV" => ["id" => "124", "name" => "Latvia", "symbol" => "€", "currency" => "EUR"],
    "LB" => ["id" => "125", "name" => "Lebanon", "symbol" => "£", "currency" => "LBP"],
    "LS" => ["id" => "126", "name" => "Lesotho", "symbol" => "L", "currency" => "LSL"],
    "LR" => ["id" => "127", "name" => "Liberia", "symbol" => "$", "currency" => "LRD"],
    "LY" => ["id" => "128", "name" => "Libyan Arab Jamahiriya", "symbol" => "د.ل", "currency" => "LYD"],
    "LI" => ["id" => "129", "name" => "Liechtenstein", "symbol" => "CHf", "currency" => "CHF"],
    "LT" => ["id" => "130", "name" => "Lithuania", "symbol" => "€", "currency" => "EUR"],
    "LU" => ["id" => "131", "name" => "Luxembourg", "symbol" => "€", "currency" => "EUR"],
    "MO" => ["id" => "132", "name" => "Macao", "symbol" => "$", "currency" => "MOP"],
    "MK" => ["id" => "133", "name" => "Macedonia, the Former Yugoslav Republic of", "symbol" => "ден", "currency" => "MKD"],
    "MG" => ["id" => "134", "name" => "Madagascar", "symbol" => "Ar", "currency" => "MGA"],
    "MW" => ["id" => "135", "name" => "Malawi", "symbol" => "MK", "currency" => "MWK"],
    "MY" => ["id" => "136", "name" => "Malaysia", "symbol" => "RM", "currency" => "MYR"],
    "MV" => ["id" => "137", "name" => "Maldives", "symbol" => "Rf", "currency" => "MVR"],
    "ML" => ["id" => "138", "name" => "Mali", "symbol" => "CFA", "currency" => "XOF"],
    "MT" => ["id" => "139", "name" => "Malta", "symbol" => "€", "currency" => "EUR"],
    "MH" => ["id" => "140", "name" => "Marshall Islands", "symbol" => "$", "currency" => "USD"],
    "MQ" => ["id" => "141", "name" => "Martinique", "symbol" => "€", "currency" => "EUR"],
    "MR" => ["id" => "142", "name" => "Mauritania", "symbol" => "MRU", "currency" => "MRO"],
    "MU" => ["id" => "143", "name" => "Mauritius", "symbol" => "₨", "currency" => "MUR"],
    "YT" => ["id" => "144", "name" => "Mayotte", "symbol" => "€", "currency" => "EUR"],
    "MX" => ["id" => "145", "name" => "Mexico", "symbol" => "$", "currency" => "MXN"],
    "FM" => ["id" => "146", "name" => "Micronesia, Federated States of", "symbol" => "$", "currency" => "USD"],
    "MD" => ["id" => "147", "name" => "Moldova, Republic of", "symbol" => "L", "currency" => "MDL"],
    "MC" => ["id" => "148", "name" => "Monaco", "symbol" => "€", "currency" => "EUR"],
    "MN" => ["id" => "149", "name" => "Mongolia", "symbol" => "₮", "currency" => "MNT"],
    "ME" => ["id" => "150", "name" => "Montenegro", "symbol" => "€", "currency" => "EUR"],
    "MS" => ["id" => "151", "name" => "Montserrat", "symbol" => "$", "currency" => "XCD"],
    "MA" => ["id" => "152", "name" => "Morocco", "symbol" => "DH", "currency" => "MAD"],
    "MZ" => ["id" => "153", "name" => "Mozambique", "symbol" => "MT", "currency" => "MZN"],
    "MM" => ["id" => "154", "name" => "Myanmar", "symbol" => "K", "currency" => "MMK"],
    "NA" => ["id" => "155", "name" => "Namibia", "symbol" => "$", "currency" => "NAD"],
    "NR" => ["id" => "156", "name" => "Nauru", "symbol" => "$", "currency" => "AUD"],
    "NP" => ["id" => "157", "name" => "Nepal", "symbol" => "₨", "currency" => "NPR"],
    "NL" => ["id" => "158", "name" => "Netherlands", "symbol" => "€", "currency" => "EUR"],
    "AN" => ["id" => "159", "name" => "Netherlands Antilles", "symbol" => "NAf", "currency" => "ANG"],
    "NC" => ["id" => "160", "name" => "New Caledonia", "symbol" => "₣", "currency" => "XPF"],
    "NZ" => ["id" => "161", "name" => "New Zealand", "symbol" => "$", "currency" => "NZD"],
    "NI" => ["id" => "162", "name" => "Nicaragua", "symbol" => "C$", "currency" => "NIO"],
    "NE" => ["id" => "163", "name" => "Niger", "symbol" => "CFA", "currency" => "XOF"],
    "NG" => ["id" => "164", "name" => "Nigeria", "symbol" => "₦", "currency" => "NGN"],
    "NU" => ["id" => "165", "name" => "Niue", "symbol" => "$", "currency" => "NZD"],
    "NF" => ["id" => "166", "name" => "Norfolk Island", "symbol" => "$", "currency" => "AUD"],
    "MP" => ["id" => "167", "name" => "Northern Mariana Islands", "symbol" => "$", "currency" => "USD"],
    "NO" => ["id" => "168", "name" => "Norway", "symbol" => "kr", "currency" => "NOK"],
    "OM" => ["id" => "169", "name" => "Oman", "symbol" => ".ع.ر", "currency" => "OMR"],
    "PK" => ["id" => "170", "name" => "Pakistan", "symbol" => "₨", "currency" => "PKR"],
    "PW" => ["id" => "171", "name" => "Palau", "symbol" => "$", "currency" => "USD"],
    "PS" => ["id" => "172", "name" => "Palestinian Territory, Occupied", "symbol" => "₪", "currency" => "ILS"],
    "PA" => ["id" => "173", "name" => "Panama", "symbol" => "B/.", "currency" => "PAB"],
    "PG" => ["id" => "174", "name" => "Papua New Guinea", "symbol" => "K", "currency" => "PGK"],
    "PY" => ["id" => "175", "name" => "Paraguay", "symbol" => "₲", "currency" => "PYG"],
    "PE" => ["id" => "176", "name" => "Peru", "symbol" => "S/.", "currency" => "PEN"],
    "PH" => ["id" => "177", "name" => "Philippines", "symbol" => "₱", "currency" => "PHP"],
    "PN" => ["id" => "178", "name" => "Pitcairn", "symbol" => "$", "currency" => "NZD"],
    "PL" => ["id" => "179", "name" => "Poland", "symbol" => "zł", "currency" => "PLN"],
    "PT" => ["id" => "180", "name" => "Portugal", "symbol" => "€", "currency" => "EUR"],
    "PR" => ["id" => "181", "name" => "Puerto Rico", "symbol" => "$", "currency" => "USD"],
    "QA" => ["id" => "182", "name" => "Qatar", "symbol" => "ق.ر", "currency" => "QAR"],
    "RE" => ["id" => "183", "name" => "Reunion", "symbol" => "€", "currency" => "EUR"],
    "RO" => ["id" => "184", "name" => "Romania", "symbol" => "lei", "currency" => "RON"],
    "RU" => ["id" => "185", "name" => "Russian Federation", "symbol" => "₽", "currency" => "RUB"],
    "RW" => ["id" => "186", "name" => "Rwanda", "symbol" => "FRw", "currency" => "RWF"],
    "BL" => ["id" => "187", "name" => "Saint Barthelemy", "symbol" => "€", "currency" => "EUR"],
    "SH" => ["id" => "188", "name" => "Saint Helena", "symbol" => "£", "currency" => "SHP"],
    "KN" => ["id" => "189", "name" => "Saint Kitts and Nevis", "symbol" => "$", "currency" => "XCD"],
    "LC" => ["id" => "190", "name" => "Saint Lucia", "symbol" => "$", "currency" => "XCD"],
    "MF" => ["id" => "191", "name" => "Saint Martin", "symbol" => "€", "currency" => "EUR"],
    "PM" => ["id" => "192", "name" => "Saint Pierre and Miquelon", "symbol" => "€", "currency" => "EUR"],
    "VC" => ["id" => "193", "name" => "Saint Vincent and the Grenadines", "symbol" => "$", "currency" => "XCD"],
    "WS" => ["id" => "194", "name" => "Samoa", "symbol" => "SAT", "currency" => "WST"],
    "SM" => ["id" => "195", "name" => "San Marino", "symbol" => "€", "currency" => "EUR"],
    "ST" => ["id" => "196", "name" => "Sao Tome and Principe", "symbol" => "Db", "currency" => "STD"],
    "SA" => ["id" => "197", "name" => "Saudi Arabia", "symbol" => "﷼", "currency" => "SAR"],
    "SN" => ["id" => "198", "name" => "Senegal", "symbol" => "CFA", "currency" => "XOF"],
    "RS" => ["id" => "199", "name" => "Serbia", "symbol" => "din", "currency" => "RSD"],
    "CS" => ["id" => "200", "name" => "Serbia and Montenegro", "symbol" => "din", "currency" => "RSD"],
    "SC" => ["id" => "201", "name" => "Seychelles", "symbol" => "SRe", "currency" => "SCR"],
    "SL" => ["id" => "202", "name" => "Sierra Leone", "symbol" => "Le", "currency" => "SLL"],
    "SG" => ["id" => "203", "name" => "Singapore", "symbol" => "$", "currency" => "SGD"],
    "SX" => ["id" => "204", "name" => "St Martin", "symbol" => "ƒ", "currency" => "ANG"],
    "SK" => ["id" => "205", "name" => "Slovakia", "symbol" => "€", "currency" => "EUR"],
    "SI" => ["id" => "206", "name" => "Slovenia", "symbol" => "€", "currency" => "EUR"],
    "SB" => ["id" => "207", "name" => "Solomon Islands", "symbol" => "Si$", "currency" => "SBD"],
    "SO" => ["id" => "208", "name" => "Somalia", "symbol" => "Sh.so.", "currency" => "SOS"],
    "ZA" => ["id" => "209", "name" => "South Africa", "symbol" => "R", "currency" => "ZAR"],
    "GS" => ["id" => "210", "name" => "South Georgia and the South Sandwich Islands", "symbol" => "£", "currency" => "GBP"],
    "SS" => ["id" => "211", "name" => "South Sudan", "symbol" => "£", "currency" => "SSP"],
    "ES" => ["id" => "212", "name" => "Spain", "symbol" => "€", "currency" => "EUR"],
    "LK" => ["id" => "213", "name" => "Sri Lanka", "symbol" => "Rs", "currency" => "LKR"],
    "SD" => ["id" => "214", "name" => "Sudan", "symbol" => ".س.ج", "currency" => "SDG"],
    "SR" => ["id" => "215", "name" => "Suriname", "symbol" => "$", "currency" => "SRD"],
    "SJ" => ["id" => "216", "name" => "Svalbard and Jan Mayen", "symbol" => "kr", "currency" => "NOK"],
    "SZ" => ["id" => "217", "name" => "Swaziland", "symbol" => "E", "currency" => "SZL"],
    "SE" => ["id" => "218", "name" => "Sweden", "symbol" => "kr", "currency" => "SEK"],
    "CH" => ["id" => "219", "name" => "Switzerland", "symbol" => "CHf", "currency" => "CHF"],
    "SY" => ["id" => "220", "name" => "Syrian Arab Republic", "symbol" => "LS", "currency" => "SYP"],
    "TW" => ["id" => "221", "name" => "Taiwan, Province of China", "symbol" => "$", "currency" => "TWD"],
    "TJ" => ["id" => "222", "name" => "Tajikistan", "symbol" => "SM", "currency" => "TJS"],
    "TZ" => ["id" => "223", "name" => "Tanzania, United Republic of", "symbol" => "TSh", "currency" => "TZS"],
    "TH" => ["id" => "224", "name" => "Thailand", "symbol" => "฿", "currency" => "THB"],
    "TL" => ["id" => "225", "name" => "Timor-Leste", "symbol" => "$", "currency" => "USD"],
    "TG" => ["id" => "226", "name" => "Togo", "symbol" => "CFA", "currency" => "XOF"],
    "TK" => ["id" => "227", "name" => "Tokelau", "symbol" => "$", "currency" => "NZD"],
    "TO" => ["id" => "228", "name" => "Tonga", "symbol" => "$", "currency" => "TOP"],
    "TT" => ["id" => "229", "name" => "Trinidad and Tobago", "symbol" => "$", "currency" => "TTD"],
    "TN" => ["id" => "230", "name" => "Tunisia", "symbol" => "ت.د", "currency" => "TND"],
    "TR" => ["id" => "231", "name" => "Turkey", "symbol" => "₺", "currency" => "TRY"],
    "TM" => ["id" => "232", "name" => "Turkmenistan", "symbol" => "T", "currency" => "TMT"],
    "TC" => ["id" => "233", "name" => "Turks and Caicos Islands", "symbol" => "$", "currency" => "USD"],
    "TV" => ["id" => "234", "name" => "Tuvalu", "symbol" => "$", "currency" => "AUD"],
    "UG" => ["id" => "235", "name" => "Uganda", "symbol" => "USh", "currency" => "UGX"],
    "UA" => ["id" => "236", "name" => "Ukraine", "symbol" => "₴", "currency" => "UAH"],
    "AE" => ["id" => "237", "name" => "United Arab Emirates", "symbol" => "إ.د", "currency" => "AED"],
    "GB" => ["id" => "238", "name" => "United Kingdom", "symbol" => "£", "currency" => "GBP"],
    "US" => ["id" => "239", "name" => "United States", "symbol" => "$", "currency" => "USD"],
    "UM" => ["id" => "240", "name" => "United States Minor Outlying Islands", "symbol" => "$", "currency" => "USD"],
    "UY" => ["id" => "241", "name" => "Uruguay", "symbol" => "$", "currency" => "UYU"],
    "UZ" => ["id" => "242", "name" => "Uzbekistan", "symbol" => "лв", "currency" => "UZS"],
    "VU" => ["id" => "243", "name" => "Vanuatu", "symbol" => "VT", "currency" => "VUV"],
    "VE" => ["id" => "244", "name" => "Venezuela", "symbol" => "Bs", "currency" => "VEF"],
    "VN" => ["id" => "245", "name" => "Viet Nam", "symbol" => "₫", "currency" => "VND"],
    "VG" => ["id" => "246", "name" => "Virgin Islands, British", "symbol" => "$", "currency" => "USD"],
    "VI" => ["id" => "247", "name" => "Virgin Islands, U.s.", "symbol" => "$", "currency" => "USD"],
    "WF" => ["id" => "248", "name" => "Wallis and Futuna", "symbol" => "₣", "currency" => "XPF"],
    "EH" => ["id" => "249", "name" => "Western Sahara", "symbol" => "MAD", "currency" => "MAD"],
    "YE" => ["id" => "250", "name" => "Yemen", "symbol" => "﷼", "currency" => "YER"],
    "ZM" => ["id" => "251", "name" => "Zambia", "symbol" => "ZK", "currency" => "ZMW"],
    "ZW" => ["id" => "252", "name" => "Zimbabwe", "symbol" => "$", "currency" => "ZWL"]
];