
    <div class="row">
        <div class="col-lg-4">
            {!!  Html::decode(Form::label('demand_type' ,'Demand Type' ,['class'=>'col-form-label text-left']))   !!}
                <div class="input-group">
                {!!  Form::select('demand_type', MarqueeHelper::demand(),null,['id'=>'demand_type','class'=>'select2 form-control mb-3 custom-select float-right','placeholder'=>'Select Demand Type'])!!}
                </div>
            {!!  Html::decode(Form::label('booking_no' ,'Booking No.' ,['class'=>'col-form-label text-left']))   !!}
            <div class="input-group">
                {!!  Form::text('custom_booking_number',null,['id'=>'booking_no','class'=>'form-control ','placeholder'=>'']) !!}
                {!!  Form::hidden('customer_id',null,['id'=>'customer_id','class'=>'form-control ','placeholder'=>'']) !!}
                {!!  Form::hidden('category','WB') !!}
                <div class="input-group-append" onClick="searchBooking()">
                    <span class="btn btn-primary"><i class="fas fa-search"></i></span>
                </div>
            </div>
        </div>
        <div class="col-lg-4">
            {!!  Html::decode(Form::label('demand_no' ,'Demand No.' ,['class'=>'col-form-label text-right']))   !!}
            <div class="input-group ">
                {!!  Form::text('demand_no',(isset($demandNo)) ? $demandNo : $model->id,['id'=>'demand_no','class'=>'form-control ','placeholder'=>'','readonly']) !!}

            </div>
            {!!  Html::decode(Form::label('narration' ,'Narration' ,['class'=>'col-form-label text-right ml-1']))   !!}
            <div class="input-group ">
                {!!  Form::textarea('narration',null,['id'=>'narration','class'=>'form-control ','placeholder'=>'Remarks' , 'rows' => 2]) !!}

            </div>
        </div>
        <div class="col-lg-4">
            {!!  Html::decode(Form::label('generated_by' ,'Generated By' ,['class'=>'col-form-label text-right']))   !!}
            <div class="input-group ">
                {!!  Form::text('generated_by',(isset($user)) ? $user->name : null,['id'=>'generated_by','class'=>'form-control ','placeholder'=>'','readonly']) !!}

            </div>
        </div>
    </div>



